name: Add to Data Challenge Project

on:
  issues:
    types: [opened, reopened]
  pull_request:
    types: [opened, reopened]
  pull_request_target:
    types: [opened, reopened]

jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - name: Add item to GitHub Project
        uses: actions/add-to-project@v0.6.0
        with:
          # For org projects:
          # https://github.com/orgs/<ORG>/projects/<PROJECT_NUMBER>
          # For user projects:
          # https://github.com/users/<USERNAME>/projects/<PROJECT_NUMBER>
          project-url: https://github.com/orgs/rges-pit/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          
